# Generated by Django 4.2.16 on 2025-03-09 00:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_picture_job_required_skills_job_responsibilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
