# Generated by Django 4.2.17 on 2025-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='wage',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
