# Generated by Django 4.2.17 on 2025-02-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_wage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='wage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
