# Generated by Django 4.2.16 on 2025-03-12 20:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
