name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4

      - name: Build and start services using docker-compose
        run: docker compose up -d --build

      - name: Run Tests inside the container
        run: |
          docker compose exec -T web pytest --disable-warnings

      - name: Stop and clean up Docker containers
        run: docker compose down

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge develop into main and push
        env:
            GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git checkout main
            git merge --no-ff develop -m "Auto-merged develop into main after successful tests"
            git push https://x-access-token:${GH_TOKEN}@github.com/Topsurpass/job_board_platform.git main
