name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "POSTGRES_DB=job_board" >> $GITHUB_ENV
          echo "POSTGRES_USER=Temz" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=Temitope_12" >> $GITHUB_ENV
          echo "POSTGRES_HOST=job_board_postgres_db" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "DEFAULT_FROM_EMAIL=admin@gmail.com" >> $GITHUB_ENV
          echo "EMAIL_HOST_PASSWORD=password" >> $GITHUB_ENV
          echo "EMAIL_HOST_USER=admin@gmail.com" >> $GITHUB_ENV
          echo "SUPPORT_EMAIL=admisupportn@gmail.com" >> $GITHUB_ENV

      - name: Build and start services using docker-compose
        # env:
        #     POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        #     POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        #     POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        #     POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        #     POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        #     CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        #     ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        #     DEFAULT_FROM_EMAIL: ${{ secrets.DEFAULT_FROM_EMAIL }}
        #     EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        #     EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        #     SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}

        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
            echo "Waiting for web service to start..."
            sleep 20

      - name: Check Docker container status
        run: |
            docker ps -a

      - name: Show logs for debugging
        run: docker compose logs web

      - name: Run Tests inside the container
        run: |
          docker compose exec -T web pytest --disable-warnings

      - name: Stop and clean up Docker containers
        run: docker compose down

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge develop into main and push
        env:
            GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git checkout main
            git merge --no-ff develop -m "Auto-merged develop into main after successful tests"
            git push https://x-access-token:${GH_TOKEN}@github.com/Topsurpass/job_board_platform.git main
